# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 12:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productfeatured_productimage_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='variation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Variation'),
        ),
    ]
