# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 17:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20170811_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sizes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=120)),
                ('size', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('instock', models.BooleanField(default=True)),
                ('inventory', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='variation',
            name='brand',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='variation',
            name='code',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='variation',
            name='size',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='sizes',
            name='variation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Variation'),
        ),
    ]
